# Generated by Django 4.2.30 on 2026-05-20 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_privacy_policy', models.BooleanField(default=False, verbose_name='Aceptó política de privacidad')),
                ('accepted_data_treatment', models.BooleanField(default=False, verbose_name='Aceptó tratamiento de datos')),
                ('policy_version', models.CharField(default='1.0', max_length=10, verbose_name='Versión de la política')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de consentimiento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_consents', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Consentimiento de privacidad',
                'verbose_name_plural': 'Consentimientos de privacidad',
                'ordering': ['-created_at'],
            },
        ),
    ]
