# Generated by Django 6.0.4 on 2026-05-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountlockout',
            options={'verbose_name': 'Bloqueo de cuenta', 'verbose_name_plural': 'Bloqueos de cuenta'},
        ),
        migrations.AlterModelOptions(
            name='loginattempt',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Intento de inicio de sesión', 'verbose_name_plural': 'Intentos de inicio de sesión'},
        ),
        migrations.AlterField(
            model_name='accountlockout',
            name='attempt_count',
            field=models.IntegerField(default=0, verbose_name='Cantidad de intentos fallidos'),
        ),
        migrations.AlterField(
            model_name='accountlockout',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='accountlockout',
            name='locked_until',
            field=models.DateTimeField(verbose_name='Bloqueado hasta'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='successful',
            field=models.BooleanField(default=False, verbose_name='¿Fue exitoso?'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora del intento'),
        ),
    ]
