# Generated by Django 4.2.30 on 2026-05-20 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_product_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('message', models.TextField(blank=True, default='', help_text='Mensaje opcional del proponente al dueño del producto solicitado.', verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('offered_product', models.ForeignKey(help_text='Producto que el proponente ofrece a cambio.', on_delete=django.db.models.deletion.CASCADE, related_name='offered_in_proposals', to='products.product', verbose_name='Producto ofrecido')),
                ('proposer', models.ForeignKey(help_text='Usuario que hace la oferta de intercambio.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Proponente')),
                ('requested_product', models.ForeignKey(help_text='Producto que el proponente desea obtener.', on_delete=django.db.models.deletion.CASCADE, related_name='requested_in_proposals', to='products.product', verbose_name='Producto solicitado')),
            ],
            options={
                'verbose_name': 'Propuesta de intercambio',
                'verbose_name_plural': 'Propuestas de intercambio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='exchangeproposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pendiente')), fields=('offered_product', 'requested_product'), name='unique_pending_proposal'),
        ),
    ]
