# Generated by Django 4.2.30 on 2026-05-20 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado de la propuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offered_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered_in_proposals', to='products.product', verbose_name='Producto Ofertado')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_exchanges', to=settings.AUTH_USER_MODEL, verbose_name='Proponente')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_exchanges', to=settings.AUTH_USER_MODEL, verbose_name='Receptor')),
                ('requested_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_in_proposals', to='products.product', verbose_name='Producto Solicitado')),
            ],
            options={
                'verbose_name': 'Propuesta de Intercambio',
                'verbose_name_plural': 'Propuestas de Intercambio',
                'ordering': ['-created_at'],
            },
        ),
    ]
