# Generated by Django 4.2.30 on 2026-05-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, help_text='Indica si el producto está disponible para intercambio.', verbose_name='Disponible'),
        ),
    ]
